# Generated by Django 5.2 on 2025-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
